baseURL = "https://koobai.com"
languageCode = "zh-cn"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "记录生活"
paginate = 5
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  twitter_handle = "@koobai"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = true
  addFrame = false
  highlightColor = '#BB2649'
  baseColor = "#FFF9F2"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#444444"
  dotColor = "#BB2649"
  description = "koobai的个人博客, hugo, 日常生活的记录, 同时分享下日常使用的软件, 平常观看的影视, 喜欢折腾的物品等。"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1