baseURL = "https://koobai.com"
languageCode = "zh-cn"
theme = "jingzhe"
themesDir = "themes"
title = "空白生活"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showPostsOnHomepage = true
  addDot = true
  baseColor = "var(--background-color)"
  baseOffsetColor = "#eaeaea"
  headingColor = "#000"
  dotColor = "var(--text-highlight-color)"

[permalinks]
  posts = '/:slug/'

[params.artalk]
    server="https://c.koobai.com"
    site="Koobai 空白生活"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'running'
    name = '锻炼'
    url = 'https://koobai.github.io/workouts'
    weight = 2