baseURL = "https://koobai.com"
languageCode = "zh-cn"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "空白生活"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  twitter_handle = "@koobai"
  showPostsOnHomepage = true
  addDot = true
  addFrame = false
  highlightColor = '#BB2649'
  baseColor = "var(--background-color)"
  baseOffsetColor = "#eaeaea"
  headingColor = "#000"
  dotColor = "#BB2649"

[permalinks]
  posts = '/:slug/'

[params.artalk]
    server="https://c.koobai.com"
    site="Koobai 空白生活"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1